version: '3.7'

services:

  postgres-bot:
    image: postgres
    container_name: postgres-container
    ports:
      - 5480:5432
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  demo-telegram-bot:
    image: telegram-bot-local
    container_name: demo-telegram-bot-container
    depends_on:
      - postgres
      - zookeeper
      - kafka
    ports:
      - 8082:8082
    environment:
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_CONNECTION: jdbc:postgresql://postgres-bot:5432/demotelegrambot
      BRANCH: DEV
